export const CONSTANTS = {
  PAGE_NAME: "SHOPPING_PAGE",
  FLOOR_TYPE: {
    COMMON: "COMMON",
    BANNER: "BANNER",
    COMPOSITE_V: "COMPOSITE_V",
    LIMIT_TIME: "LIMIT_TIME",
    VIP_SPECIAL: "VIP_SPECIAL",
    GUESS_LIKE: "GUESS_LIKE",
  },
};
